version: ~> 1.0
language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
os:
  - linux
virt: lxd
sudo: false
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
