version: ~> 1.0
language: go
go:
  - 1.15.x
os:
  - linux
dist: focal
virt: lxd
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
