name: GoBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...
    - name: Test (with coverage file)
      run: go test -v -race -coverprofile=coverage.out ./...
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
